### ISSUE TITLE
New version available

### ISSUE THREAD

**Issue by davellanedam** [Widcket/dreamhost-phalcon-install#2]
Hello! Great job sharing extensions for dh, found it very useful, but there's now a new version of phalcon (2.0.10), can you please upload the new .so, or even better share the script you use to compile it, so others can build their own?. Thanks a lot!

**Comment by danielcosta** [comment]
Yes, please share the script you use because I want to make it available to PHP 7 now, and we could PR it to this repo.

**Comment by Widcket** [comment]
Closed with ad99075f23a3bd3c7ffe90e74e1bdf8aba75ad4b
